//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace calcular_de_notas
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class notasPolitecnicoInternacionalEntities : DbContext
    {
        public notasPolitecnicoInternacionalEntities()
            : base("name=notasPolitecnicoInternacionalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tecnologiaDesarrolloSoftware> tecnologiaDesarrolloSoftware { get; set; }
    }
}
