//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace calcular_de_notas
{
    using System;
    using System.Collections.Generic;
    
    public partial class tecnologiaDesarrolloSoftware
    {
        public int id_Alumnos { get; set; }
        public string Nombre_Alumnos { get; set; }
        public decimal Nota_primer_corte { get; set; }
        public decimal Nota_segundo_corte { get; set; }
        public decimal Nota_tercer_corte { get; set; }
        public decimal Nota_Final { get; set; }
        public string CodigoAlumno { get; set; }
    }
}
